#!/usr/bin/env node
// The scheduled compile has to run the *same* arithmetic as the app — one
// definition, or the baking list the kitchen sees and the one the app predicts
// drift apart. Cloud Functions only deploy their own directory, so the shared
// modules are copied in rather than duplicated by hand.
//
// Runs automatically before the emulators start and before any deploy.

import { cpSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'functions', 'shared')

rmSync(target, { recursive: true, force: true })
mkdirSync(join(target, 'lib'), { recursive: true })

cpSync(join(root, 'src', 'config.js'), join(target, 'config.js'))
cpSync(join(root, 'src', 'lib'), join(target, 'lib'), { recursive: true })

const banner = '// Copied from src/ by scripts/sync-shared.mjs. Do not edit here.\n'
for (const file of ['config.js', ...readdirSync(join(target, 'lib')).map((f) => join('lib', f))]) {
  const path = join(target, file)
  const { readFileSync } = await import('node:fs')
  writeFileSync(path, banner + readFileSync(path, 'utf8'))
}

writeFileSync(join(target, '.gitignore'), '# generated by scripts/sync-shared.mjs\n*\n')
console.log(`✓ shared logic copied into functions/shared`)
