import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Connection details for the Baker's Inn Firebase project.
///
/// Written by hand rather than generated by `flutterfire configure`, so that
/// adding a platform does not need another CLI installed. The values come from
/// `firebase apps:sdkconfig`, and each platform has its own API key — an Android
/// key is restricted to the app's package name, a web key to the site's domain.
///
/// None of this is secret. A Firebase client config ships inside every copy of
/// the app that is installed; what protects the takings is `firestore.rules`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Baker\'s Inn is built for Android tablets and the web. '
          '$defaultTargetPlatform has no Firebase configuration here.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxy4O27FeCq6BYkC-M6Gv75Ko6DPHjses',
    appId: '1:404233973127:web:9bfde345aeb478271b7722',
    messagingSenderId: '404233973127',
    projectId: 'bakers-inn-pk',
    authDomain: 'bakers-inn-pk.firebaseapp.com',
    storageBucket: 'bakers-inn-pk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6g1NasNP5eYSiYaeLayKVLR84i9zonzE',
    appId: '1:404233973127:android:2c5bd471633182a31b7722',
    messagingSenderId: '404233973127',
    projectId: 'bakers-inn-pk',
    storageBucket: 'bakers-inn-pk.firebasestorage.app',
  );
}
